# SPDX-License-Identifier: AGPL-3.0-or-later

name: Go
on:
  push:
    branches:
    - master
  pull_request: {}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
        - '1.20'
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
    - uses: actions/checkout@v1
    - run: cd server; go generate ./...
    # /go/pkg/mod/github.com/kataras/pio@v0.0.10/printer.go:226:16: undefined: terminal.IsTerminal
    #- run: cd server; CGO_ENABLED=0 GOOS=aix GOARCH=ppc64 GOPPC64=power8 go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=aix GOARCH=ppc64 GOPPC64=power9 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 GOAMD64=v1 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 GOAMD64=v2 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 GOAMD64=v3 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 GOAMD64=v4 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=dragonfly GOARCH=amd64 GOAMD64=v1 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=dragonfly GOARCH=amd64 GOAMD64=v2 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=dragonfly GOARCH=amd64 GOAMD64=v3 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=dragonfly GOARCH=amd64 GOAMD64=v4 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=freebsd GOARCH=386 GO386=softfloat go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=freebsd GOARCH=386 GO386=sse2 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=freebsd GOARCH=amd64 GOAMD64=v1 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=freebsd GOARCH=amd64 GOAMD64=v2 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=freebsd GOARCH=amd64 GOAMD64=v3 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=freebsd GOARCH=amd64 GOAMD64=v4 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=freebsd GOARCH=arm GOARM=5 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=freebsd GOARCH=arm GOARM=6 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=freebsd GOARCH=arm GOARM=7 go build ./...
    # /go/pkg/mod/github.com/creack/pty@v1.1.18/pty_freebsd.go:53:20: undefined: fiodgnameArg
    #- run: cd server; CGO_ENABLED=0 GOOS=freebsd GOARCH=riscv64 go build ./...
    # /go/pkg/mod/github.com/kataras/iris/v12@v12.2.0/core/netutil/tcp_soreuse_control_unix.go:19:59: undefined: unix.SO_REUSEPORT
    #- run: cd server; CGO_ENABLED=0 GOOS=illumos GOARCH=amd64 GOAMD64=v1 go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=illumos GOARCH=amd64 GOAMD64=v2 go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=illumos GOARCH=amd64 GOAMD64=v3 go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=illumos GOARCH=amd64 GOAMD64=v4 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=linux GOARCH=386 GO386=softfloat go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=linux GOARCH=386 GO386=sse2 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOAMD64=v1 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOAMD64=v2 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOAMD64=v3 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOAMD64=v4 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=5 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=6 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=7 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=linux GOARCH=loong64 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=linux GOARCH=mips GOMIPS=softfloat go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=linux GOARCH=mips GOMIPS=hardfloat go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=linux GOARCH=mipsle GOMIPS=softfloat go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=linux GOARCH=mipsle GOMIPS=hardfloat go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=linux GOARCH=mips64 GOMIPS64=softfloat go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=linux GOARCH=mips64 GOMIPS64=hardfloat go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=linux GOARCH=mips64le GOMIPS64=softfloat go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=linux GOARCH=mips64le GOMIPS64=hardfloat go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=linux GOARCH=ppc64 GOPPC64=power8 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=linux GOARCH=ppc64 GOPPC64=power9 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=linux GOARCH=ppc64le GOPPC64=power8 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=linux GOARCH=ppc64le GOPPC64=power9 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=linux GOARCH=riscv64 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=linux GOARCH=s390x go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=netbsd GOARCH=386 GO386=softfloat go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=netbsd GOARCH=386 GO386=sse2 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=netbsd GOARCH=amd64 GOAMD64=v1 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=netbsd GOARCH=amd64 GOAMD64=v2 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=netbsd GOARCH=amd64 GOAMD64=v3 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=netbsd GOARCH=amd64 GOAMD64=v4 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=netbsd GOARCH=arm GOARM=5 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=netbsd GOARCH=arm GOARM=6 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=netbsd GOARCH=arm GOARM=7 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=openbsd GOARCH=386 GO386=softfloat go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=openbsd GOARCH=386 GO386=sse2 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=openbsd GOARCH=amd64 GOAMD64=v1 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=openbsd GOARCH=amd64 GOAMD64=v2 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=openbsd GOARCH=amd64 GOAMD64=v3 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=openbsd GOARCH=amd64 GOAMD64=v4 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=openbsd GOARCH=arm GOARM=5 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=openbsd GOARCH=arm GOARM=6 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=openbsd GOARCH=arm GOARM=7 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=openbsd GOARCH=arm64 go build ./...
    # /go/pkg/mod/github.com/kataras/pio@v0.0.10/printer.go:226:16: undefined: terminal.IsTerminal
    #- run: cd server; CGO_ENABLED=0 GOOS=plan9 GOARCH=386 GO386=softfloat go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=plan9 GOARCH=386 GO386=sse2 go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=plan9 GOARCH=amd64 GOAMD64=v1 go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=plan9 GOARCH=amd64 GOAMD64=v2 go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=plan9 GOARCH=amd64 GOAMD64=v3 go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=plan9 GOARCH=amd64 GOAMD64=v4 go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=plan9 GOARCH=arm GOARM=5 go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=plan9 GOARCH=arm GOARM=6 go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=plan9 GOARCH=arm GOARM=7 go build ./...
    # /go/pkg/mod/github.com/kataras/iris/v12@v12.2.0/core/netutil/tcp_soreuse_control_unix.go:19:59: undefined: unix.SO_REUSEPORT
    #- run: cd server; CGO_ENABLED=0 GOOS=solaris GOARCH=amd64 GOAMD64=v1 go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=solaris GOARCH=amd64 GOAMD64=v2 go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=solaris GOARCH=amd64 GOAMD64=v3 go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=solaris GOARCH=amd64 GOAMD64=v4 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=windows GOARCH=386 GO386=softfloat go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=windows GOARCH=386 GO386=sse2 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=windows GOARCH=amd64 GOAMD64=v1 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=windows GOARCH=amd64 GOAMD64=v2 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=windows GOARCH=amd64 GOAMD64=v3 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=windows GOARCH=amd64 GOAMD64=v4 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=windows GOARCH=arm GOARM=5 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=windows GOARCH=arm GOARM=6 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=windows GOARCH=arm GOARM=7 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=windows GOARCH=arm64 go build ./...
