name: Go
on:
  push:
    branches:
    - master
  pull_request: {}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
        # /go/pkg/mod/github.com/kataras/iris/v12@v12.1.8/core/errgroup/errgroup.go:109:9: undefined: errors.Unwrap
        #- v: '1.11'
        #  i386: '387'
        #- v: '1.12'
        #  i386: '387'
        - v: '1.13'
          i386: '387'
        - v: '1.14'
          i386: '387'
        - v: '1.15'
          i386: '387'
        - v: '1.16'
          i386: softfloat
        - v: '1.17'
          i386: softfloat
        - v: '1.18'
          i386: softfloat
        - v: '1.19'
          i386: softfloat
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go.v }}
    - uses: actions/checkout@v1
    - run: cd server; go generate ./...
    # /go/pkg/mod/github.com/kataras/pio@v0.0.10/printer.go:226:16: undefined: terminal.IsTerminal
    #- run: cd server; CGO_ENABLED=0 GOOS=aix GOARCH=ppc64 GOPPC64=power8 go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=aix GOARCH=ppc64 GOPPC64=power9 go build ./...
    # /usr/bin/ld: cannot find -lgcc
    #- run: cd server; CGO_ENABLED=0 GOOS=android GOARCH=386 GO386=${{ matrix.go.i386 }} go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=android GOARCH=386 GO386=sse2 go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=android GOARCH=amd64 GOAMD64=v1 go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=android GOARCH=amd64 GOAMD64=v2 go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=android GOARCH=amd64 GOAMD64=v3 go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=android GOARCH=amd64 GOAMD64=v4 go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=android GOARCH=arm GOARM=5 go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=android GOARCH=arm GOARM=6 go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=android GOARCH=arm GOARM=7 go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=android GOARCH=arm64 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 GOAMD64=v1 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 GOAMD64=v2 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 GOAMD64=v3 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 GOAMD64=v4 go build ./...

    - run: cd server; CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build ./...
      # /tmp/go-link-969410686/go.o: file not recognized: file format not recognized
      if: matrix.go.v >= 1.16

    - run: cd server; CGO_ENABLED=0 GOOS=dragonfly GOARCH=amd64 GOAMD64=v1 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=dragonfly GOARCH=amd64 GOAMD64=v2 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=dragonfly GOARCH=amd64 GOAMD64=v3 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=dragonfly GOARCH=amd64 GOAMD64=v4 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=freebsd GOARCH=386 GO386=${{ matrix.go.i386 }} go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=freebsd GOARCH=386 GO386=sse2 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=freebsd GOARCH=amd64 GOAMD64=v1 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=freebsd GOARCH=amd64 GOAMD64=v2 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=freebsd GOARCH=amd64 GOAMD64=v3 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=freebsd GOARCH=amd64 GOAMD64=v4 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=freebsd GOARCH=arm GOARM=5 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=freebsd GOARCH=arm GOARM=6 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=freebsd GOARCH=arm GOARM=7 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=illumos GOARCH=amd64 GOAMD64=v1 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=illumos GOARCH=amd64 GOAMD64=v2 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=illumos GOARCH=amd64 GOAMD64=v3 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=illumos GOARCH=amd64 GOAMD64=v4 go build ./...
    # gcc: error: unrecognized command-line option '-framework'
    #- run: cd server; CGO_ENABLED=0 GOOS=ios GOARCH=arm64 go build ./...
    # /go/pkg/mod/github.com/kataras/pio@v0.0.10/printer.go:226:16: undefined: terminal.IsTerminal
    #- run: cd server; CGO_ENABLED=0 GOOS=js GOARCH=wasm go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=js GOARCH=wasm GOWASM=satconv go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=js GOARCH=wasm GOWASM=signext go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=linux GOARCH=386 GO386=${{ matrix.go.i386 }} go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=linux GOARCH=386 GO386=sse2 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOAMD64=v1 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOAMD64=v2 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOAMD64=v3 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOAMD64=v4 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=5 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=6 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=7 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build ./...
    # /go/pkg/mod/golang.org/x/sys@v0.0.0-20200602225109-6fdc65e7d980/unix/affinity_linux.go:14:35: undefined: _NCPUBITS
    #- run: cd server; CGO_ENABLED=0 GOOS=linux GOARCH=loong64 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=linux GOARCH=mips GOMIPS=softfloat go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=linux GOARCH=mips GOMIPS=hardfloat go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=linux GOARCH=mipsle GOMIPS=softfloat go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=linux GOARCH=mipsle GOMIPS=hardfloat go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=linux GOARCH=mips64 GOMIPS64=softfloat go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=linux GOARCH=mips64 GOMIPS64=hardfloat go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=linux GOARCH=mips64le GOMIPS64=softfloat go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=linux GOARCH=mips64le GOMIPS64=hardfloat go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=linux GOARCH=ppc64 GOPPC64=power8 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=linux GOARCH=ppc64 GOPPC64=power9 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=linux GOARCH=ppc64le GOPPC64=power8 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=linux GOARCH=ppc64le GOPPC64=power9 go build ./...

    - run: cd server; CGO_ENABLED=0 GOOS=linux GOARCH=riscv64 go build ./...
      if: matrix.go.v >= 1.14

    - run: cd server; CGO_ENABLED=0 GOOS=linux GOARCH=s390x go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=netbsd GOARCH=386 GO386=${{ matrix.go.i386 }} go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=netbsd GOARCH=386 GO386=sse2 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=netbsd GOARCH=amd64 GOAMD64=v1 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=netbsd GOARCH=amd64 GOAMD64=v2 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=netbsd GOARCH=amd64 GOAMD64=v3 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=netbsd GOARCH=amd64 GOAMD64=v4 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=netbsd GOARCH=arm GOARM=5 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=netbsd GOARCH=arm GOARM=6 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=netbsd GOARCH=arm GOARM=7 go build ./...
    # /go/pkg/mod/github.com/creack/pty@v1.1.13/pty_openbsd.go:27:10: undefined: ptmget
    #- run: cd server; CGO_ENABLED=0 GOOS=openbsd GOARCH=386 GO386=${{ matrix.go.i386 }} go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=openbsd GOARCH=386 GO386=sse2 go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=openbsd GOARCH=amd64 GOAMD64=v1 go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=openbsd GOARCH=amd64 GOAMD64=v2 go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=openbsd GOARCH=amd64 GOAMD64=v3 go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=openbsd GOARCH=amd64 GOAMD64=v4 go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=openbsd GOARCH=arm GOARM=5 go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=openbsd GOARCH=arm GOARM=6 go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=openbsd GOARCH=arm GOARM=7 go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=openbsd GOARCH=arm64 go build ./...
    # /go/pkg/mod/github.com/kataras/pio@v0.0.10/printer.go:226:16: undefined: terminal.IsTerminal
    #- run: cd server; CGO_ENABLED=0 GOOS=plan9 GOARCH=386 GO386=${{ matrix.go.i386 }} go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=plan9 GOARCH=386 GO386=sse2 go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=plan9 GOARCH=amd64 GOAMD64=v1 go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=plan9 GOARCH=amd64 GOAMD64=v2 go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=plan9 GOARCH=amd64 GOAMD64=v3 go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=plan9 GOARCH=amd64 GOAMD64=v4 go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=plan9 GOARCH=arm GOARM=5 go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=plan9 GOARCH=arm GOARM=6 go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=plan9 GOARCH=arm GOARM=7 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=solaris GOARCH=amd64 GOAMD64=v1 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=solaris GOARCH=amd64 GOAMD64=v2 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=solaris GOARCH=amd64 GOAMD64=v3 go build ./...
    - run: cd server; CGO_ENABLED=0 GOOS=solaris GOARCH=amd64 GOAMD64=v4 go build ./...
    # internal/ws/ws.go:142:22: undefined: pty.Start
    #- run: cd server; CGO_ENABLED=0 GOOS=windows GOARCH=386 GO386=${{ matrix.go.i386 }} go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=windows GOARCH=386 GO386=sse2 go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=windows GOARCH=amd64 GOAMD64=v1 go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=windows GOARCH=amd64 GOAMD64=v2 go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=windows GOARCH=amd64 GOAMD64=v3 go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=windows GOARCH=amd64 GOAMD64=v4 go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=windows GOARCH=arm GOARM=5 go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=windows GOARCH=arm GOARM=6 go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=windows GOARCH=arm GOARM=7 go build ./...
    #- run: cd server; CGO_ENABLED=0 GOOS=windows GOARCH=arm64 go build ./...
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
        # /go/pkg/mod/github.com/kataras/iris/v12@v12.1.8/core/errgroup/errgroup.go:109:9: undefined: errors.Unwrap
        #- '1.11'
        #- '1.12'
        - '1.13'
        - '1.14'
        - '1.15'
        - '1.16'
        - '1.17'
        - '1.18'
        - '1.19'
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
    - uses: actions/checkout@v1
    - run: cd server; go generate ./...
    - run: cd server; go test -race -v ./...
